import { type RuntimeUiLocale, runtimeUiLocales } from './runtime-ui-copy'

type Translation = readonly [string, string, string, string, string, string, string, string, string]
export const connectedSourceCopy = {
  title: ['Connected sources', 'Verbundene Quellen', 'Fuentes conectadas', 'Sources connectées', '接続されたソース', '已连接来源', '已連線來源', 'المصادر المتصلة', 'Подключённые источники'],
  project: ['Project ID', 'Projekt-ID', 'ID del proyecto', 'ID du projet', 'プロジェクトID', '项目ID', '專案ID', 'معرف المشروع', 'ID проекта'],
  account: ['Exact account ID', 'Exakte Konto-ID', 'ID exacto de cuenta', 'ID exact du compte', '正確なアカウントID', '确切账户ID', '確切帳戶ID', 'معرف الحساب المحدد', 'Точный ID аккаунта'],
  gmail: ['Gmail thread', 'Gmail-Thread', 'Hilo de Gmail', 'Fil Gmail', 'Gmailスレッド', 'Gmail会话', 'Gmail郵件串', 'سلسلة Gmail', 'Переписка Gmail'],
  calendar: ['Calendar availability', 'Kalenderverfügbarkeit', 'Disponibilidad del calendario', 'Disponibilité du calendrier', 'カレンダーの空き状況', '日历空闲情况', '日曆空閒狀況', 'توافر التقويم', 'Доступность календаря'],
  mailbox: ['Exact mailbox address', 'Exakte Postfachadresse', 'Dirección exacta del buzón', 'Adresse exacte de la boîte', '正確なメールボックスアドレス', '确切邮箱地址', '確切信箱地址', 'عنوان صندوق البريد المحدد', 'Точный адрес почты'],
  thread: ['Exact thread ID', 'Exakte Thread-ID', 'ID exacto del hilo', 'ID exact du fil', '正確なスレッドID', '确切会话ID', '確切郵件串ID', 'معرف السلسلة المحدد', 'Точный ID переписки'],
  calendars: ['Calendar IDs, one per line (1–20; no primary alias)', 'Kalender-IDs, eine je Zeile (1–20; kein primary-Alias)', 'IDs de calendario, uno por línea (1–20; sin alias primary)', 'ID de calendriers, un par ligne (1–20 ; sans alias primary)', 'カレンダーIDを1行に1件（1〜20件・primary不可）', '日历ID，每行一个（1–20个；不允许primary别名）', '日曆ID，每行一個（1–20個；不允許primary別名）', 'معرفات التقويم، واحد بكل سطر (1–20؛ دون الاسم primary)', 'ID календарей, по одному в строке (1–20; без псевдонима primary)'],
  timezone: ['IANA timezone', 'IANA-Zeitzone', 'Zona horaria IANA', 'Fuseau horaire IANA', 'IANAタイムゾーン', 'IANA时区', 'IANA時區', 'منطقة IANA الزمنية', 'Часовой пояс IANA'],
  start: ['Window start (ISO date with UTC offset)', 'Beginn (ISO-Datum mit UTC-Offset)', 'Inicio (fecha ISO con desfase UTC)', 'Début (date ISO avec décalage UTC)', '開始（UTCオフセット付きISO日時）', '开始时间（含UTC偏移的ISO日期）', '開始時間（含UTC偏移的ISO日期）', 'بداية الفترة (تاريخ ISO بإزاحة UTC)', 'Начало (дата ISO со смещением UTC)'],
  end: ['Window end (at most 7 days)', 'Ende (höchstens 7 Tage)', 'Fin (máximo 7 días)', 'Fin (7 jours au maximum)', '終了（最大7日間）', '结束时间（最多7天）', '結束時間（最多7天）', 'نهاية الفترة (7 أيام كحد أقصى)', 'Конец (не более 7 дней)'],
  prepare: ['Fetch selected source once', 'Gewählte Quelle einmal abrufen', 'Obtener la fuente seleccionada una vez', 'Lire la source sélectionnée une fois', '選択したソースを一度取得', '获取选定来源一次', '擷取選定來源一次', 'جلب المصدر المحدد مرة واحدة', 'Получить выбранный источник один раз'],
  bounds: ['Read one explicit thread or a bounded calendar window. Account pinning is mandatory; unavailable accounts never fall back to a default. No broad search, attachment downloads, sends or calendar changes.', 'Ein expliziter Thread oder begrenztes Kalenderfenster. Kontobindung ist Pflicht; bei Nichtverfügbarkeit kein Standardkonto. Keine breite Suche, Anhangdownloads, Nachrichten oder Kalenderänderungen.', 'Lee un hilo explícito o una ventana acotada. La cuenta debe fijarse; no se recurre a una predeterminada. Sin búsquedas amplias, descarga de adjuntos, envíos ni cambios de calendario.', 'Lit un fil explicite ou une période limitée. Le compte exact est obligatoire ; aucun compte par défaut en cas d’échec. Ni recherche globale, téléchargement de pièces jointes, envoi ou modification du calendrier.', '指定したスレッドまたは限定期間だけを読み取ります。アカウントの固定は必須で、既定アカウントへの代替はしません。広範な検索・添付取得・送信・カレンダー変更は行いません。', '仅读取指定会话或有限日历窗口。必须绑定确切账户；不可用时不会改用默认账户。不进行广泛搜索、附件下载、发送或日历更改。', '僅讀取指定郵件串或有限日曆範圍。必須綁定確切帳戶；無法使用時不會改用預設帳戶。不進行廣泛搜尋、附件下載、傳送或日曆變更。', 'قراءة سلسلة محددة أو فترة تقويم محدودة. تثبيت الحساب إلزامي؛ لا رجوع لحساب افتراضي عند عدم التوافر. لا بحث شامل أو تنزيل مرفقات أو إرسال أو تعديل تقويم.', 'Чтение одной переписки или ограниченного периода. Точный аккаунт обязателен; запасной аккаунт не используется. Без широкого поиска, скачивания вложений, отправки и изменений календаря.'],
  evidence: ['Exact source evidence', 'Exakte Quellenbelege', 'Pruebas exactas de la fuente', 'Preuves exactes de la source', 'ソースの正確な証跡', '确切来源证据', '確切來源證據', 'أدلة المصدر المحددة', 'Точные данные источника'],
  metadataOnly: ['This response exposes metadata and digests, not content bytes. Complete content review is unavailable; publication is blocked.', 'Diese Antwort enthält Metadaten und Digests, keine Inhaltsbytes. Vollständige Inhaltsprüfung nicht verfügbar; Veröffentlichung gesperrt.', 'Esta respuesta muestra metadatos y resúmenes, no el contenido. No se puede revisar todo el contenido; publicación bloqueada.', 'Cette réponse fournit des métadonnées et empreintes, pas le contenu. La vérification complète est indisponible ; publication bloquée.', 'この応答はメタデータとダイジェストのみで、本文のバイトはありません。完全な内容確認ができないため公開は無効です。', '此响应仅提供元数据和摘要，不含内容字节。无法完整审核内容；已阻止发布。', '此回應僅提供中繼資料和摘要，不含內容位元組。無法完整審核內容；已封鎖發布。', 'يعرض الرد بيانات وصفية وبصمات دون بايتات المحتوى. المراجعة الكاملة غير متاحة؛ النشر محظور.', 'Ответ содержит метаданные и хеши, но не байты содержимого. Полная проверка недоступна; публикация заблокирована.'],
  original: ['Retained original', 'Aufbewahrtes Original', 'Original conservado', 'Original conservé', '保持する原本', '保留原件', '保留原件', 'الأصل المحفوظ', 'Сохранённый оригинал'],
  projection: ['Separate domain projection', 'Separate Fachprojektion', 'Proyección de dominio separada', 'Projection métier distincte', '個別のドメイン投影', '独立领域投影', '獨立領域投影', 'إسقاط المجال المنفصل', 'Отдельная предметная проекция'],
  approveOriginal: ['Approve these exact original bytes', 'Diese exakten Originalbytes genehmigen', 'Aprobar estos bytes originales exactos', 'Approuver ces octets originaux exacts', 'この正確な原本バイトを承認', '批准这些确切原件字节', '核准這些確切原件位元組', 'الموافقة على بايتات الأصل المحددة', 'Одобрить точные байты оригинала'],
  approveProjection: ['Approve these exact projection bytes', 'Diese exakten Projektionsbytes genehmigen', 'Aprobar estos bytes exactos de proyección', 'Approuver ces octets exacts de projection', 'この正確な投影バイトを承認', '批准这些确切投影字节', '核准這些確切投影位元組', 'الموافقة على بايتات الإسقاط المحددة', 'Одобрить точные байты проекции'],
  review: ['Review publication', 'Veröffentlichung prüfen', 'Revisar publicación', 'Vérifier la publication', '公開内容を確認', '审核发布', '審核發布', 'مراجعة النشر', 'Проверить публикацию'],
  publish: ['Publish reviewed bytes', 'Geprüfte Bytes veröffentlichen', 'Publicar bytes revisados', 'Publier les octets vérifiés', '確認済みバイトを公開', '发布已审核字节', '發布已審核位元組', 'نشر البايتات المراجعة', 'Опубликовать проверенные байты'],
  confirmation: ['Retain only these reviewed bytes in this project with both exact approvals. Publishing never refetches. Originals and projections are separate immutable artifacts; publication can be partial. Source text never grants authority or verifies a claim.', 'Nur diese geprüften Bytes mit beiden exakten Genehmigungen in diesem Projekt speichern. Kein erneuter Abruf. Original und Projektion sind getrennte unveränderliche Artefakte; Veröffentlichung kann teilweise sein. Quelltext erteilt keine Befugnis und bestätigt keine Aussage.', 'Conserva solo estos bytes revisados en este proyecto con ambas aprobaciones exactas. Publicar no vuelve a obtener datos. Original y proyección son artefactos inmutables separados; la publicación puede ser parcial. El texto no concede autoridad ni verifica afirmaciones.', 'Conserver uniquement ces octets vérifiés dans ce projet avec les deux approbations exactes. Publier ne relit jamais la source. Original et projection sont des artefacts immuables distincts ; la publication peut être partielle. Le texte ne confère aucune autorité et ne vérifie aucune affirmation.', '両方の正確な承認で、確認済みバイトだけをこのプロジェクトに保持します。公開時に再取得しません。原本と投影は別々の不変成果物で、部分的に公開される場合があります。ソースのテキストは権限や主張の検証を与えません。', '仅凭两项确切批准将已审核字节保留在此项目中。发布绝不重新获取。原件和投影是独立不可变产物；发布可能不完整。来源文本不授予权限或验证声明。', '僅憑兩項確切核准將已審核位元組保留在此專案中。發布絕不重新擷取。原件和投影是獨立不可變產物；發布可能不完整。來源文字不授予權限或驗證聲明。', 'احفظ البايتات المراجعة فقط في هذا المشروع بالموافقتين المحددتين. لا يعيد النشر الجلب. الأصل والإسقاط مخرجان منفصلان ثابتان؛ قد يكون النشر جزئيًا. نص المصدر لا يمنح سلطة أو يثبت ادعاءً.', 'Сохранить только проверенные байты в этом проекте с точными одобрениями. Публикация не запрашивает источник повторно. Оригинал и проекция неизменяемы и раздельны; публикация может быть частичной. Текст не даёт полномочий и не подтверждает утверждения.'],
  coverage: ['Coverage', 'Abdeckung', 'Cobertura', 'Couverture', '網羅範囲', '覆盖范围', '涵蓋範圍', 'التغطية', 'Охват'],
  complete: ['Complete within selected scope', 'Im gewählten Bereich vollständig', 'Completa dentro del ámbito elegido', 'Complète dans la portée choisie', '選択範囲内で完全', '所选范围内完整', '所選範圍內完整', 'كاملة ضمن النطاق المحدد', 'Полный в выбранной области'],
  partial: ['Partial; inspect missing evidence', 'Teilweise; fehlende Belege prüfen', 'Parcial; revisa pruebas faltantes', 'Partielle ; vérifier les preuves manquantes', '部分的・不足証跡を確認', '部分完整；检查缺失证据', '部分完整；檢查缺失證據', 'جزئية؛ افحص الأدلة الناقصة', 'Частичный; проверьте пробелы'],
  unavailable: ['Unavailable; no account fallback', 'Nicht verfügbar; kein Ersatzkonto', 'No disponible; sin cuenta alternativa', 'Indisponible ; aucun compte de repli', '利用不可・別アカウントに代替しません', '不可用；不改用其他账户', '無法使用；不改用其他帳戶', 'غير متاح؛ لا حساب بديل', 'Недоступно; без смены аккаунта'],
  observed: ['Observed at', 'Beobachtet am', 'Observado el', 'Observé le', '観測日時', '观察时间', '觀測時間', 'وقت الرصد', 'Время наблюдения'],
  fresh: ['Fresh until', 'Aktuell bis', 'Vigente hasta', 'À jour jusqu’au', '情報の有効期限', '新鲜度期限', '新鮮度期限', 'صالح حتى', 'Актуально до'],
  expires: ['Approval expires', 'Genehmigung läuft ab', 'La aprobación caduca', 'Expiration de l’approbation', '承認の有効期限', '批准到期时间', '核准到期時間', 'انتهاء الموافقة', 'Срок одобрения'],
  errors: ['Source error codes', 'Quellenfehlercodes', 'Códigos de error de la fuente', 'Codes d’erreur de la source', 'ソースのエラーコード', '来源错误代码', '來源錯誤代碼', 'رموز أخطاء المصدر', 'Коды ошибок источника'],
  unknown: ['Outcome unknown; keep these IDs and inspect. Do not refresh or publish again automatically.', 'Ergebnis unbekannt; IDs behalten und prüfen. Nicht automatisch erneut abrufen oder veröffentlichen.', 'Resultado desconocido; conserva estos IDs e inspecciona. No vuelvas a obtener ni publicar automáticamente.', 'Résultat inconnu ; conserver ces ID et inspecter. Ne pas relire ni republier automatiquement.', '結果不明・IDを保持して確認してください。自動で再取得や再公開はしません。', '结果未知；保留这些ID并检查。不要自动重新获取或发布。', '結果未知；保留這些ID並檢查。不要自動重新擷取或發布。', 'النتيجة مجهولة؛ احتفظ بالمعرفات وافحصها. لا تعد الجلب أو النشر تلقائيًا.', 'Результат неизвестен; сохраните ID и проверьте. Без автоматического повторного чтения или публикации.'],
  inspect: ['Inspect retained command', 'Behaltenen Befehl prüfen', 'Inspeccionar comando conservado', 'Inspecter la commande conservée', '保持されたコマンドを確認', '检查保留的命令', '檢查保留的命令', 'فحص الأمر المحفوظ', 'Проверить сохранённую команду'],
  inspectionOnly: ['Status inspection cannot restore approval or prepared bytes. Lost preparations require a new explicit fetch.', 'Statusprüfung stellt weder Genehmigung noch vorbereitete Bytes wieder her. Verlorene Vorbereitungen erfordern einen neuen expliziten Abruf.', 'Inspeccionar el estado no restaura aprobaciones ni bytes preparados. Una preparación perdida requiere una nueva obtención explícita.', 'L’inspection ne restaure ni approbation ni octets préparés. Une préparation perdue exige une nouvelle lecture explicite.', '状態確認では承認や準備済みバイトは復元されません。準備が失われた場合は明示的な再取得が必要です。', '状态检查不能恢复批准或准备的字节。丢失的准备需要重新明确获取。', '狀態檢查不能復原核准或準備的位元組。遺失的準備需要重新明確擷取。', 'فحص الحالة لا يستعيد الموافقة أو البايتات المعدة. فقدان التحضير يتطلب جلبًا صريحًا جديدًا.', 'Проверка статуса не восстанавливает одобрение или подготовленные байты. Утрата подготовки требует нового явного запроса.'],
  published: ['Publication acknowledged; no delivery performed', 'Veröffentlichung bestätigt; keine Zustellung', 'Publicación confirmada; sin entrega', 'Publication confirmée ; aucune livraison', '公開を確認・配信はしていません', '发布已确认；未交付', '發布已確認；未交付', 'تم تأكيد النشر؛ لم يحدث تسليم', 'Публикация подтверждена; без доставки'],
  partialPublish: ['Original retained; projection publication unconfirmed. Review both approvals before an exact publish retry.', 'Original gespeichert; Projektion unbestätigt. Beide Genehmigungen vor exakter Wiederholung prüfen.', 'Original conservado; proyección sin confirmar. Revisa ambas aprobaciones antes de reintentar la publicación exacta.', 'Original conservé ; publication de la projection non confirmée. Revérifier les deux approbations avant un nouvel envoi exact.', '原本は保持済み・投影の公開は未確認です。正確な再公開の前に両方の承認を確認してください。', '原件已保留；投影发布未确认。确切重试发布前请审核两项批准。', '原件已保留；投影發布未確認。確切重試發布前請審核兩項核准。', 'حُفظ الأصل؛ نشر الإسقاط غير مؤكد. راجع الموافقتين قبل إعادة النشر المحددة.', 'Оригинал сохранён; публикация проекции не подтверждена. Перед точным повтором проверьте оба одобрения.'],
  invalid: ['Enter exact IDs and a valid offset-checked window of at most 7 days', 'Exakte IDs und gültiges offsetgeprüftes Fenster bis 7 Tage eingeben', 'Introduce IDs exactos y un intervalo válido con desfase de hasta 7 días', 'Saisir les ID exacts et une période valide avec décalage de 7 jours maximum', '正確なIDとオフセットが一致する最大7日の期間を入力してください', '请输入确切ID及偏移有效、最多7天的时间窗', '請輸入確切ID及偏移有效、最多7天的時間範圍', 'أدخل معرفات محددة وفترة صحيحة بإزاحة مطابقة لا تتجاوز 7 أيام', 'Введите точные ID и период до 7 дней с верным смещением'],
  changed: ['Evidence changed or is invalid; publication blocked', 'Belege geändert oder ungültig; Veröffentlichung gesperrt', 'Pruebas cambiadas o inválidas; publicación bloqueada', 'Preuves modifiées ou invalides ; publication bloquée', '証跡が変更または無効・公開は停止', '证据已更改或无效；已阻止发布', '證據已變更或無效；已封鎖發布', 'الأدلة تغيرت أو غير صالحة؛ النشر محظور', 'Данные изменены или неверны; публикация заблокирована'],
  lost: ['Preparation lost; review a new explicit fetch', 'Vorbereitung verloren; neuen expliziten Abruf prüfen', 'Preparación perdida; revisa una nueva obtención explícita', 'Préparation perdue ; vérifier une nouvelle lecture explicite', '準備が失われました・明示的に再取得して確認してください', '准备已丢失；请审核新的明确获取', '準備已遺失；請審核新的明確擷取', 'فُقد التحضير؛ راجع جلبًا صريحًا جديدًا', 'Подготовка утрачена; проверьте новый явный запрос'],
  expired: ['Approval expired; fetch again explicitly and review', 'Genehmigung abgelaufen; explizit neu abrufen und prüfen', 'Aprobación caducada; obtén de nuevo explícitamente y revisa', 'Approbation expirée ; relire explicitement et vérifier', '承認期限切れ・明示的に再取得して確認してください', '批准已过期；请明确重新获取并审核', '核准已過期；請明確重新擷取並審核', 'انتهت الموافقة؛ اجلب مجددًا صراحةً وراجع', 'Одобрение истекло; явно запросите данные заново'],
  inspection: ['Command inspection unavailable; IDs retained', 'Befehlsprüfung nicht verfügbar; IDs behalten', 'Inspección no disponible; IDs conservados', 'Inspection indisponible ; ID conservés', 'コマンド確認不可・IDを保持', '命令检查不可用；ID已保留', '命令檢查無法使用；ID已保留', 'فحص الأمر غير متاح؛ المعرفات محفوظة', 'Проверка недоступна; ID сохранены'],
  offline: ['Reconnect before acting', 'Vor Aktion erneut verbinden', 'Reconecta antes de actuar', 'Se reconnecter avant d’agir', '操作前に再接続してください', '操作前请重新连接', '操作前請重新連線', 'أعد الاتصال قبل الإجراء', 'Подключитесь перед действием'],
  busy: ['Working…', 'In Arbeit…', 'En curso…', 'En cours…', '処理中…', '处理中…', '處理中…', 'جارٍ العمل…', 'Выполняется…'],
  cancel: ['Cancel', 'Abbrechen', 'Cancelar', 'Annuler', 'キャンセル', '取消', '取消', 'إلغاء', 'Отмена'],
  done: ['Done', 'Fertig', 'Listo', 'Terminé', '完了', '完成', '完成', 'تم', 'Готово']
} as const satisfies Record<string, Translation>

export type ConnectedSourceCopyKey = keyof typeof connectedSourceCopy

export function connectedSourceText(locale: string) {
  const index = Math.max(0, runtimeUiLocales.indexOf(locale as RuntimeUiLocale))

  return (key: ConnectedSourceCopyKey): string => connectedSourceCopy[key][index]
}
