#!/usr/bin/env -S bash -c 'exec "$BASH" "$(dirname "$0")/_hermes-python" "$0" "$@"'
"""Generate the BE01 reference from the runtime's typed configuration fields."""

from __future__ import annotations

import argparse
from dataclasses import fields
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from agent.agent_identity import (
    AgentIdentityConfig,
    AgentPolicy,
    ID_PATTERN,
    SCHEMA_VERSION,
)  # noqa: E402

DEFAULT_OUTPUT = ROOT / "docs/build/agent-identity-reference.md"


def render_reference() -> str:
    lines = [
        "# Agent identity configuration reference",
        "",
        "<!-- Generated by scripts/gen_agent_identity_reference.py; do not edit by hand. -->",
        "",
        f"Policy schema version: {SCHEMA_VERSION}.",
        "",
        "The optional `agent_identity` root is read from effective profile configuration. "
        "An absent root or an empty mapping preserves legacy behavior. Any other malformed "
        "value fails closed before provider construction. There is no environment-variable "
        "or display-name override and no `enabled` switch.",
        "",
    ]
    for heading, cls in (
        ("Root: agent_identity", AgentIdentityConfig),
        ("Policy: agents.<configured-id> and child_policy", AgentPolicy),
    ):
        lines += [
            f"## {heading}",
            "",
            "| Field | Type | Required | Meaning |",
            "| --- | --- | --- | --- |",
        ]
        for item in fields(cls):
            if not item.metadata.get("config"):
                continue
            annotation = str(item.type).replace("|", "\\|")
            lines.append(
                f"| `{item.name}` | `{annotation}` | {'yes' if item.metadata.get('required') else 'no'} | {item.metadata['description']} |"
            )
        lines.append("")
    lines += [
        "## Identity and lifecycle rules",
        "",
        f"- Principal, profile, agent and session IDs must match `{ID_PATTERN}`; "
        "Windows reserved device names are rejected. IDs cannot contain paths, dots or spaces.",
        "- Exactly `primary_agent_id` has the primary role and personal_mcp backend. All other configured IDs have specialist role and builtin backend.",
        "- The `child_` agent namespace is reserved. Trusted construction generates `child_<32 lowercase hex>` IDs; model names and prompts cannot choose one.",
        "- A child requires its parent context and an explicit child_policy. Its grants are the intersection of parent grants and child policy, including MCP tools and secrets. Project and egress collections must remain empty in BE01.",
        "- Personal MCP servers and personal credential references are forbidden in every specialist and child policy, even when profiles are shared.",
        "- Grant names are exact and case-sensitive. Wildcards and duplicate grants are rejected. Missing grant collections are empty, never allow-all. An MCP server with no granted tools is not admitted.",
        "- Unknown fields, unsupported versions, type errors and unknown active/primary IDs are rejected. Inventory fields on resolved policies are derived from configuration and cannot be supplied as policy grants.",
        "",
        "## Resume, redaction and scope",
        "",
        "Bindings store identity IDs, lifecycle, parent ID, binding revision, policy/config digests and a home digest. "
        "An existing session with no binding is refused under enabled policy. A mismatched session ID, "
        "changed policy/configuration, home or active agent also refuses resume. Starting a new session "
        "is the explicit migration boundary; newer records never downgrade to legacy access.",
        "",
        "AgentContext is frozen and contains only its binding, policy, config digest and canonical profile home. "
        "Redacted inspection includes provenance and credential-reference counts, never credential values or raw configuration. "
        "Bind/read validate the current effective home; contextvars preserve identity across copy_context thread hops. "
        "Profile lifecycle code must bind home, secrets and terminal policy together before installing identity.",
        "",
        "Configuration changes apply at the next construction/session boundary. The current conversation's "
        "policy and prompt remain immutable. Restoring a saved session requires its original compatible binding.",
        "",
        "## Enforcement boundaries",
        "",
        "These contracts describe authority, not an OS sandbox. Nonempty egress_purposes and project_grants "
        "are rejected until BE05/BE07 provide concrete dispatch enforcement. This phase does not implement personal MCP memory "
        "semantics or specialist memory persistence; those are BE08 dependencies. No raw AIAgent, "
        "secret dictionary or generic service locator is exposed by AgentContext.",
        "",
        "## Regeneration",
        "",
        "Run `.venv/bin/python scripts/gen_agent_identity_reference.py` after schema changes. "
        "Use `--check` to verify freshness without writing. The focused identity tests compare this "
        "reference with the current typed schema.",
        "",
    ]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args(argv)
    rendered = render_reference()
    if args.check:
        if (
            not args.output.exists()
            or args.output.read_text(encoding="utf-8") != rendered
        ):
            print(f"Agent identity reference is stale: {args.output}", file=sys.stderr)
            return 1
        return 0
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(rendered, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
