#!/usr/bin/env -S bash -c 'exec "$BASH" "$(dirname "$0")/_hermes-python" "$0" "$@"'
"""Deterministically render the opt-in runtime budget field contract."""
from pathlib import Path
import argparse
import sys

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
from agent.budget_account import BUDGET_CONFIG_FIELDS

OUTPUT = ROOT / "docs/build/runtime-budget-reference.md"


def render_reference():
    lines = ["# Runtime budget configuration reference", "",
             "<!-- Generated by scripts/gen_runtime_budget_reference.py; do not edit. -->", "",
             "The optional effective-profile `runtime_budget` mapping is empty by default. "
             "A nonempty policy requires schema version 1 and configured durable agent identity. "
             "Null, partial and unknown-field policies fail closed. No environment override is provided.", "",
             "| Field | Contract |", "| --- | --- |"]
    lines += [f"| `{name}` | {description} |" for name, description in BUDGET_CONFIG_FIELDS.items()]
    lines += ["", "## Enforcement and limitations", "",
              "The policy snapshot is immutable for an accepted run. Root IDs come from accepted durable commands. "
              "A child requires a trusted persisted parent handoff and its own accepted command/lease; "
              "reservations atomically debit every ancestor. Until a trusted mission boundary is available, "
              "all continuations in one session share its first root. Start a new session for an explicit new allocation. "
              "Restart, retries, failover, queued waiting and policy removal do not reset or enlarge ceilings.", "",
              "The initial adapter supports one nonstreaming text-only OpenAI SDK chat completion. "
              "The exact route/model, provider framing overhead and output parameter must be verified by the operator. "
              "The entire serialized envelope, including tools and history, is conservatively charged as UTF-8 bytes "
              "plus framing overhead before dispatch. No prompt is silently truncated. SDK retries are disabled; "
              "every application retry reserves another attempt and input/output maximum. Provider slots and "
              "aggregate duration are shared across main and auxiliary calls. Request deadlines request local cancellation.", "",
              "Cost mode additionally requires explicit verified worst-case rates, including any cache/reasoning multipliers. "
              "No prices are supplied or guessed. Settled cost is policy-priced usage, not a verified vendor invoice "
              "and not an invoice guarantee. Tokens mode has no spend ceiling and reports cost as untracked. "
              "Missing usage, transport failures and unknown upstream outcomes retain conservative allocations; "
              "a local socket close does not prove remote work stopped or refund usage. A late result without "
              "current ownership cannot release its reservation. Overruns block further dispatch as debt.", "",
              "Only the built-in in-memory todo_list handler and trusted delegation orchestration currently have "
              "tool cost contracts. Delegate descendants reserve independently. Opaque tools (including terminal, "
              "MCP, media, memory services and external loops), embedding requests, server-side tools, raw streams, "
              "non-OpenAI adapters, opaque extensions and callable plugin hooks/middleware/events are refused under enabled budgets. "
              "Policy hooks are rejected, never silently skipped; startup callbacks also require an admitted bounded adapter. Compaction is supported "
              "only when its auxiliary request uses the certified text adapter. Existing capability, isolation, "
              "egress and local IterationBudget restrictions remain independently enforced.", "",
              "Dispatched work may outlive local cancellation. Such work retains durable resource/usage uncertainty "
              "rather than being reported as cancelled upstream or as a successful complete result. Completed artifacts "
              "and partial output remain in their original transcript/journal projections.", "",
              "Regenerate with `.venv/bin/python scripts/gen_runtime_budget_reference.py`; use `--check` for freshness.", ""]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render_reference()
    if args.check:
        return 0 if OUTPUT.exists() and OUTPUT.read_text() == rendered else 1
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(rendered)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
